CREATE DATABASE SISTEMALIBRERIA_EQUIPO211E;
USE SISTEMALIBRERIA_EQUIPO211E;

CREATE TABLE CATEGORIA
(
    ID INT IDENTITY PRIMARY KEY,
    DESCRIPCION VARCHAR (100) NOT NULL,
    ES_GENERO BIT NOT NULL,
    BORRADO BIT NOT NULL
);

CREATE TABLE PROVEEDOR
(
    ID INT IDENTITY PRIMARY KEY,
    DESCRIPCION VARCHAR (100) NOT NULL,
    ES_EDITORIAL BIT NOT NULL,
    EMAIL VARCHAR (100) NOT NULL,
    NUMERO_TELEFONICO VARCHAR (20) NOT NULL,
    BORRADO BIT NOT NULL,
);

CREATE TABLE IDIOMA
(
    ID INT IDENTITY PRIMARY KEY,
    DESCRIPCION VARCHAR (100) NOT NULL,
    BORRADO BIT NOT NULL
);

CREATE TABLE AUTOR
(
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    BORRADO BIT NOT NULL,
);

CREATE TABLE PRODUCTO 
(
    ID INT IDENTITY PRIMARY KEY,
    DESCRIPCION VARCHAR (100) NOT NULL,
    STOCK_MINIMO INT NOT NULL, 
    STOCK_MAXIMO INT NOT NULL,
    ID_PROVEEDOR INT NOT NULL,
    PRECIO FLOAT NOT NULL,
    PRODUCTO_ESTUDIANTIL BIT NOT NULL,
    CANTIDAD_PAGINAS INT NOT NULL,
    ID_AUTOR INT,
    ID_IDIOMA INT,
    BORRADO BIT NOT NULL,
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID),
    FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR (ID),
    FOREIGN KEY (ID_IDIOMA) REFERENCES IDIOMA (ID)
);

CREATE TABLE DETALLE_CATEGORIA
(
    ID INT IDENTITY PRIMARY KEY,
    ID_PRODUCTO INT NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    BORRADO BIT NOT NULL,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE ROL_USUARIO
(
    ID INT IDENTITY PRIMARY KEY,
    DESCRIPCION VARCHAR (100) NOT NULL,
    BORRADO BIT NOT NULL,
);

CREATE TABLE MODULO 
(
    ID INT IDENTITY PRIMARY KEY,
    DESCRIPCION VARCHAR (100) NOT NULL,
    BORRADO BIT NOT NULL,
)

CREATE TABLE PERMISOS
(
    ID INT IDENTITY PRIMARY KEY,
    ID_ROL INT NOT NULL,
    ID_MODULO INT NOT NULL,
    BORRADO BIT NOT NULL
    FOREIGN KEY (ID_ROL) REFERENCES ROL_USUARIO(ID),
    FOREIGN KEY (ID_MODULO) REFERENCES MODULO(ID)
);

CREATE TABLE EMPLEADO
(
    ID INT IDENTITY PRIMARY KEY,
    CEDULA VARCHAR (30) NOT NULL,
    NOMBRE_COMPLETO VARCHAR (100) NOT NULL,
    CONTRASENA VARCHAR (100) NOT NULL,
    NUMERO_TELEFONICO VARCHAR(20),
    EMAIL VARCHAR (100),
    ID_ROL INT NOT NULL,
    EMPLEADO_VIGENTE BIT NOT NULL,
    BORRADO BIT NOT NULL,
    FOREIGN KEY (ID_ROL) REFERENCES ROL_USUARIO(ID)
);

CREATE TABLE SUCURSALES 
(
    ID INT IDENTITY PRIMARY KEY,
    UBICACION VARCHAR(200),
    NUMERO_TELEFONICO VARCHAR(150),
    BORRADO BIT NOT NULL
);

CREATE TABLE BODEGA
(
    ID INT IDENTITY PRIMARY KEY,
    ID_PRODUCTO INT NOT NULL,
    ID_SUCURSAL INT NOT NULL,
    CANTIDAD INT NOT NULL,
    BORRADO BIT NOT NULL
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID),
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID)
);
CREATE TABLE ENCABEZADO_ENTRADA 
(
    ID INT IDENTITY PRIMARY KEY,
    ID_SUCURSAL INT NOT NULL,
    ID_EMPLEADO INT NOT NULL,
    FECHA DATE NOT NULL,
    BORRADO BIT NOT NULL,
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES(ID),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID)
);
CREATE TABLE DETALLE_ENTRADA 
(
    ID INT IDENTITY PRIMARY KEY,
    ID_ENTRADA INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL,
    BORRADO BIT NOT NULL,
    FOREIGN KEY (ID_ENTRADA) REFERENCES ENCABEZADO_ENTRADA (ID),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID)
);
