DELIMITER //
CREATE PROCEDURE SpIngresarDetalle(IN idEnt INT, IN idProd INT, IN cant INT)
BEGIN
    INSERT INTO DETALLE_ENTRADA (ID_ENTRADA, ID_PRODUCTO, CANTIDAD, BORRADO)
    VALUES (idEnt, idProd, cant, false);
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SpActualizarDetalle(IN idEnt INT, IN idProd INT, IN cant INT)
BEGIN
    UPDATE DETALLE_ENTRADA
    SET ID_PRODUCTO = idProd, CANTIDAD = cant
    WHERE ID_ENTRADA = idEnt;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SpBuscarEntradasFecha(IN fechaEnt DATE)
BEGIN
    SELECT e.ID, e.ID_SUCURSAL, e.ID_EMPLEADO, d.ID_PRODUCTO, d.CANTIDAD 
    FROM ENCABEZADO_ENTRADA as e, DETALLE_ENTRADA as d
    WHERE e.FECHA = fechaEnt
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SpBuscarTodoEntradas()
BEGIN 
    SELECT e.ID, e.ID_SUCURSAL, e.ID_EMPLEADO, e.FECHA, d.ID_PRODUCTO, d.CANTIDAD 
    FROM ENCABEZADO_ENTRADA as e, DETALLE_ENTRADA as d
END //
DELIMITER ;
