DELIMITER //
CREATE PROCEDURE SpIngresarRolUsuario (IN descrip varchar(100))
BEGIN
	INSERT INTO ROL_USUARIO (DESCRIPCION, BORRADO)
	VALUES (descrip, false);
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SpActualizarRolUsuario (IN descrip varchar(100), IN idRol INT)
BEGIN
	UPDATE ROL_USUARIO
    SET DESCRIPCION = descrip
    WHERE ID = idRol;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SpBuscarRolUsuario(IN idRol INT)
BEGIN
	SELECT * FROM ROL_USUARIO
    WHERE ID = idRol AND BORRADO = false;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SpBuscarTodoRolUsuario()
BEGIN
	SELECT * FROM ROL_USUARIO
	WHERE BORRADO = false;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SpBorrarRolUsuario(IN idRol INT)
BEGIN
	UPDATE ROL_USUARIO
    SET BORRADO = true
    WHERE ID = idRol;
END //
DELIMITER ;