/*REALIZAR CORRECCIONES URGENTES*/
DELIMITER //
CREATE PROCEDURE SpIngresarDetalleCategoria(IN idProd INT, IN idCat INT)
BEGIN 
    INSERT INTO DETALLE_CATEGORIA (ID_PRODUCTO, ID_CATEGORIA, BORRADO)
    VALUES (idProd, idCat, false);
END //
DELIMITER ;

/*
DELIMITER //
CREATE PROCEDURE SpActualizar
DELIMITER ;
*/

DELIMITER // 
CREATE PROCEDURE SpBorrarDetalleCategoria(IN idDet INT)
BEGIN
    UPDATE DETALLE_CATEGORIA 
    SET BORRADO = true
    WHERE ID = idDet;
END //
DELIMITER ;

/*Correccion*/
DELIMITER //
CREATE PROCEDURE SpBuscarCategoriasProducto(IN idProd INT)
BEGIN
    SELECT p.ID, p.DESCRIPCION, p.PRODUCTO_ESTUDIANTIL, c.ID_CATEGORIA FROM PRODUCTO as p, DETALLE_CATEGORIA as c
    WHERE p.ID = idProd AND c.ID = idProd;
END //
DELIMITER ;