DELIMITER //
CREATE PROCEDURE SpIngresarDetalleCategoria(IN idProd INT, IN idCat INT)
BEGIN 
    INSERT INTO DETALLE_CATEGORIA (ID_PRODUCTO, ID_CATEGORIA, BORRADO)
    VALUES (idProd, idCat, false);
END //
DELIMITER ;

DELIMITER // 
CREATE PROCEDURE SpBorrarDetalleCategoria(IN idDet INT)
BEGIN
    UPDATE DETALLE_CATEGORIA 
    SET BORRADO = true
    WHERE ID = idDet;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SpBuscarCategoriasProducto(IN idProd INT)
BEGIN
    SELECT p.ID, p.DESCRIPCION, p.PRODUCTO_ESTUDIANTIL, c.ID_CATEGORIA, a.DESCRIPCION
    FROM PRODUCTO as p, DETALLE_CATEGORIA as c, CATEGORIA as a
    WHERE p.ID = idProd AND c.ID_PRODUCTO = idProd AND a.ID = c.ID_CATEGORIA AND BORRADO = false;
END //
DELIMITER ;