DELIMITER //
CREATE PROCEDURE SpIngresarDetalleCategoria(IN idProd INT, IN idCat INT)
BEGIN 
    INSERT INTO DETALLE_CATEGORIA (ID_PRODUCTO, ID_CATEGORIA)
    VALUES (idProd, idCat);
END
DELIMITER ;