DELIMITER //
CREATE PROCEDURE SpIngresarPermisos(IN rol INT, IN idMod INT)
BEGIN 
    INSERT INTO PERMISOS (ID_ROL, ID_MODULO, BORRADO)
    VALUES (idRol, idMod, false);
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SpActualizarPermisos(IN rol INT, IN idMod INT, IN idPerm INT)
BEGIN 
    UPDATE PERMISOS
    SET ID_ROL = rol,
    ID_MODULO = idMod
    WHERE ID = idPerm;
END //
DELIMITER ;

DELIMITER // 
CREATE PROCEDURE SpBorrarPermisos(IN idPerm INT)
BEGIN
    UPDATE PERMISOS
    SET BORRADO = true
    WHERE ID = idPerm;
END //
DELIMITER ;

/*
    PENDIENTES LAS SELECCIONES DE PERMISOS POR USUARIO Y ROLES
*/
DELIMITER //
CREATE PROCEDURE SpBuscarPermisosUsuario(IN idUsuario INT)
BEGIN
    SELECT e.CEDULA, e.NOMBRE_COMPLETO, 
END //
DELIMITER ;