DELIMITER //
CREATE PROCEDURE SpIngresarBodega(IN idProd INT, IN idSuc INT, IN cant INT)
BEGIN
    INSERT INTO BODEGA (ID_PRODUCTO, ID_SUCURSAL, CANTIDAD, BORRADO)
    VALUES (idProd, idSuc, cant, false);
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SpAumentarInventario(IN idProd INT, IN idSuc INT, IN cant INT)
BEGIN 
    UPDATE BODEGA
    SET CANTIDAD = cant
    WHERE ID_PRODUCTO = idProd AND ID_SUCURSAL = idSuc;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SpBuscarProductoSucursal(IN idProd INT, IN idSuc INT)
BEGIN
    SELECT p.DESCRIPCION, b.ID_SUCURSAL, b.CANTIDAD
    FROM PRODUCTO AS p, BODEGA as b
    WHERE b.ID_PRODUCTO = idProd AND p.ID = b.ID AND b.ID_SUCURSAL = idSuc;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SpVerBodega(IN idSuc INT)
BEGIN
    SELECT p.DESCRIPCION, b.CANTIDAD
    FROM PRODUCTO AS p, BODEGA as b
    WHERE b.ID_SUCURSAL = idSuc AND b.ID_PRODUCTO = p.ID;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SpVerInventario()
BEGIN
    SELECT * FROM BODEGA;
END //
DELIMITER ;